[package]
name = "zero-emit-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }
zero-ast = { workspace = true }

[dev-dependencies]
wasmparser = "0.220"
wasmtime = { version = "26", default-features = false, features = ["cranelift", "runtime"] }

[lints]
workspace = true
