[package]
name = "zero-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "zero"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
zero-diag = { workspace = true }
zero-driver = { workspace = true }
zero-lexer = { workspace = true }
zero-parser = { workspace = true }
zero-target = { workspace = true }

[lints]
workspace = true
